config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_up', to: redirect('/404')  # Redirect to a 404 page or any other desired page
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: "users/sessions",
    registrations: 'registrations'
  }


  
  devise_scope :user do
    get 'complete_information', to: 'registrations#complete_information'
  end
  root to: "pages#home"

  resources "terrains", only:[:show,:index] do
    collection do
      get 'find_terrain_by_address'
    end
    resources "matches", only: [:index,:show] do
      post 'join_team', on: :member
    end

  end
  resources "user_team", only: [:create, :update, :destroy]
  resources "matches", only: [:new,:create]
  resources "users", only: [:show, :edit, :update]
end

app/models/terrain.rb
class Terrain < ApplicationRecord
  has_one_attached :photo

  # for searching
  include PgSearch::Model
  pg_search_scope :search_terrain,
  against: [ :name, :price, :address ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
  #
  has_many :matches
  # validates :name, uniqueness: { scope: :address, message: "the name and address must be unique" }
  # validates :price , comparison: { greater_than: 0 }
  # validates :name , length: {minimum: 3, message: "short name"}
  # validates :name , length: {maximum: 25, message: "long name"}
  # validates :address , length: {minimum: 1, message: "short adrress"}
end

app/controllers/terrains_controller.rb
class TerrainsController < ApplicationController
  # before action
  # before_action :terrain_params
  skip_before_action :authenticate_user!, only: :index

  before_action :set_terrain, only: %i[show]

  # index
  def index
    q = params[:q]
    @terrains = Terrain.search_terrain(q)
  end
  # show
  def show
    # ...
  end
  # new
  def new
    @terrain = Terrain.new
  end
  def create
    @terrain = Terrain.new(match_params)
    @terrain.user = current_user
    if @terrain.save!
      redirect_to match_path(@terrain)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # find terraing using address
  def find_terrain_by_address
    address = params[:address]
    @terrain_names = Terrain.where(address: address).pluck(:name)
    render json: { terrain_names: @terrain_names }
  end



  private

  # match params
  def terrain_params
    params.require(:terrain).permit(:name,:address,:price)
  end
  # find match in db using :id
  def set_terrain
    @terrain = Terrain.find(params[:id])
  end

end

app/helpers/terrains_helper.rb
module TerrainsHelper
end

app/views/terrains/index.html.erb
  <div class="container" id="show" data-controller="terrains">
      <div class="search container">

      </div>
     <% @terrains.each do |terrain| %>
      <div class="plan">
        <div class="inner">
          <span class="pricing">
            <span>
              <%= terrain.price %> DH
            </span>
          </span>
          <p class="title" style="margin-top:13px;"><%= terrain.name %></p>
          <div class="d-flex">
            <i class="fa-solid fa-location-dot" style="color: #58ca64;margin-top: 0"></i>
            <p style="height:20px;margin-bottom:50px;">&nbsp;&nbsp;<%= terrain.address %></p>
          </div>
          <p class="info" style="color: white;height:200px;overflow:hidden;"><%= terrain.desc %></p>
          <div class="action">
          <%= link_to "visit", terrain_path(terrain), class: "button"%>
          </div>
        </div>
      </div>
      <% end %>

  </div>

app/views/terrains/show.html.erb
<div id="terrain">


  <%# the available games %>
  <div class="terrain-games-container">
  <div class="terrain-container">
    <h2> <%= @terrain.name%></h2>
    <div class="terrain">
      <div class="terrain-image">
      </div>
      <div class="terrain-info">
        <p><i class="fa-solid fa-money-bill"></i> <%= @terrain.price%> MAD</p>
        <section class="openinghours">
          <div class="openinghourscontent section">
            <div class="header">
              <h2>Opening hours</h2>
              <span><small class="openorclosed">We are</small></span>
            </div>
            <table class="opening-hours-table">
              <tr id="Monday" itemprop="openingHours">
                <td>Monday</td>
                <td class="opens">09:00</td>
                <td>-</td>
                <td class="closes">18:00</td>
              </tr>
              <tr id="Tuesday" itemprop="openingHours" >
                <td>Tuesday</td>
                <td class="opens">09:00</td>
                <td>-</td>
                <td class="closes">23:00</td>
              </tr>
              <tr id="Wednesday" itemprop="openingHours" >
                <td>Wednesday</td>
                <td class="opens">09:00</td>
                <td>-</td>
                <td class="closes">23:00</td>
              </tr>
              <tr id="Thursday" itemprop="openingHours" >
                <td>Thursday</td>
                <td class="opens">09:00</td>
                <td>-</td>
                <td class="closes">23:00</td>
              </tr>
              <tr id="Friday" itemprop="openingHours" >
                <td>Friday</td>
                <td class="opens">09:00</td>
                <td>-</td>
                <td class="closes">22:00</td>
              </tr>
              <tr id="Saturday" itemprop="openingHours" >
                <td>Saturday</td>
                <td class="opens">10:00</td>
                <td>-</td>
                <td class="closes">23:00</td>
              </tr>
              <tr id="Sunday" itemprop="openingHours">
                <td>Sunday</td>
                <td class="opens">11:00</td>
                <td>-</td>
                <td class="closes">22:00</td>
              </tr>
            </table>
          </div>
        </section>
      </div>
    </div>

  </div>
    <div class="master" data-controller="date-navigation">
      <h2>Available Matches</h2>
    </div>
    <article class="terrain-games">
      <% @terrain.matches.each do |game| %>
        <div class="match">
          <%= cl_image_tag game.user.photo.key, class: "avatar" %>
          <p><%=game.user.first_name%> <%=game.user.last_name%></p>
          <p><%= game.date %></p>
          <%= link_to "Details", terrain_match_path(@terrain, game) %>
        </div>
        <%end%>
    </article>
  </div>
</div>