config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_up', to: redirect('/404')  # Redirect to a 404 page or any other desired page
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: "users/sessions",
    registrations: 'registrations'
  }


  
  devise_scope :user do
    get 'complete_information', to: 'registrations#complete_information'
  end
  root to: "pages#home"

  resources "terrains", only:[:show,:index] do
    collection do
      get 'find_terrain_by_address'
    end
    resources "matches", only: [:index,:show] do
      post 'join_team', on: :member
    end

  end
  resources "user_team", only: [:create, :update, :destroy]
  resources "matches", only: [:new,:create]
  resources "users", only: [:show, :edit, :update]
end

app/views/pages/home.html.erb
<div id="home">



      <section class="home_sec">
        <div class="hero-container">
            <p class="slogan">

                Kick, Connect, Compete: Where football Passion Unites!
            </p>

            <%# <img src="Penalty.png" alt="" class="goal"> %>
        </div>

        <div class="searAyman">
            <form class="form" action="/terrains" method="get">
                <label for="search">
                <%# search icon %>

                <div class="search">
                  <svg viewBox="0 0 24 24" aria-hidden="true"  class="r-14j79pv r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-4wgw6l r-f727ji r-bnwqim r-1plcrui r-lrvibr">
                      <g>
                        <path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path>
                      </g>
                  </svg>
                </div>

                <%# end search icon %>
                <input class="input" type="text" required=""  placeholder="Find you next game..." id="search" name="q" style="text-indent:20px;">


                </label>
            </form>

            <button class="btn">
                <svg height="24" width="24" fill="#FFFFFF" viewBox="0 0 24 24" data-name="Layer 1" id="Layer_1" class="sparkle">
                    <path d="M10,21.236,6.755,14.745.264,11.5,6.755,8.255,10,1.764l3.245,6.491L19.736,11.5l-6.491,3.245ZM18,21l1.5,3L21,21l3-1.5L21,18l-1.5-3L18,18l-3,1.5ZM19.333,4.667,20.5,7l1.167-2.333L24,3.5,21.667,2.333,20.5,0,19.333,2.333,17,3.5Z"></path>
                </svg>

                <%= link_to "Create game", new_match_path,class:"text",style: "text-decoration:none;" %>

            </button>
        </div>
        </section>
          <section >

          <div class="homeMidTop">
          <div class="innerWrapper paddTop-10">

         <h2>N9asro The first sports guide in Morocco</h2><p><br></p><h2>

          </h2><p>N9asro is an application designed to address the frustration stemming from the challenge of finding fellow players or teams to engage in various activities.</p><p><br></p><p>  Born out of the pain of struggling to connect with like-minded individuals, N9asro is your solution to discover potential playmates, showcase your skills, and join a community that shares your passion for sports and activities. Say goodbye to the struggle of finding a buddy or team – with N9asro, your next game is just a click away!</p><p><br></p>
              </div>
          </div>
      </section>

      <section class="card-section">

          <!-- Add your content here -->

          <div class="about-container row">
            <div class="section-title">

              <h1 > Meet The Team</h1>
            </div>
            <div class="card">
                <div class="circle"></div>
                <div class="circle"></div>
                <div class="card-inner">
                <div class="card-border-top">
              </div>
              <div class="img">
                 <img src="https://avatars.githubusercontent.com/u/94233481?v=4" alt="profile_image">
              </div>

              <span >Fadel ellah ERRAMI</span>
              <p class = "img-span">Enthusiastic junior web developer with a passion for coding and a strong foundation in HTML, CSS, and JavaScript. Committed to delivering high-quality, responsive websites.</p>
              <div class="card__icons d-flex justify-content-evenly ">
                    <a href="https://www.linkedin.com/in/fadel-ellah-errami-879b13207/"style="color:green" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a href="https://github.com/FADELELLAHerrami"style="color:green" target="_blank"><i class="fab fa-github"></i></a>
                    <a href="https://www.facebook.com/"style="color:green" target="_blank"><i class="fab fa-facebook"></i></a>
                  </div>
                </div>

            </div>
            <div class="card">
                <div class="circle"></div>
                <div class="circle"></div>
                <div class="card-inner">
                <div class="card-border-top">
              </div>
              <div class="img">
                   <img src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1702409240/bkvj6jcaiuvcbisuifx9.jpg" alt="profile_image">
              </div>
              <span>Oussama Essoufi</span>
              <p class = "img-span">Junior web developer with a meticulous approach to coding and a keen eye for detail. Proficient in front-end technologies, including HTML5, CSS3, and JavaScript</p>
              <div class="card__icons d-flex justify-content-evenly pt-2">
                    <a href="https://www.linkedin.com/in/oussama-essoufi-3a180a197/"style="color:green" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a href="https://github.com/Essoufi-oussama"style="color:green" target="_blank"><i class="fab fa-github"></i></a>
                    <a href="https://www.facebook.com/"style="color:green" target="_blank"><i class="fab fa-facebook"></i></a>
                  </div>
                </div>
            </div>
            <div class="card">
                <div class="circle"></div>
                <div class="circle"></div>
                <div class="card-inner">
                <div class="card-border-top">
              </div>
              <div class="img">
                <img src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1702540852/i9zuf4phlfeledeh4nvl.jpg" alt="profile_image">
              </div>
              <span> Ayoub Idbaih</span>
              <p class = "img-span">Passionate junior web developer with a deep love for technology and a strong desire to make an impact.  building responsive websites using modern web technologies</p>
              <div class="card__icons d-flex justify-content-evenly pt-2">
                    <a href="https://www.linkedin.com/in/ayoub-idbaih-610625239/" style="color:green" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a href="https://github.com/ayoubidbaih49" style="color:green" target="_blank"><i class="fab fa-github"></i></a>
                    <a href="https://www.facebook.com/" style="color:green"target="_blank"><i class="fab fa-facebook"></i></a>
                  </div>
                </div>

            </div>
            <div class="card">
                <div class="circle"></div>
                <div class="circle"></div>
                <div class="card-inner">
                <div class="card-border-top">
              </div>
              <div class="img">
                <img src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1702541409/zcey3ssbq6oewbauwx0t.jpg" alt="profile_image">
              </div>
              <span> Ayman Afifi</span>
              <p class = "img-span">Junior web developer with a collaborative mindset and excellent communication skills., bringing strong skills in front-end development and a proactive attitude.</p>
              <div class="card__icons d-flex justify-content-evenly pt-2">
                    <a href="https://www.linkedin.com/in/aymane-aafifi-a6662218a/"style="color:green" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a href="https://github.com/aymaneaafifi"style="color:green" target="_blank"><i class="fab fa-github"></i></a>
                    <a href="https://www.facebook.com/" style="color:green"target="_blank"><i class="fab fa-facebook"></i></a>
                  </div>
                </div>
            </div>
          </div>
        </section>
        <section class="homeBottom row">
          <div class="col">
          <img width="300px" height="300px"  src="https://jobintech.academy/wp-content/uploads/2023/05/cropped-Logo-Jobintech-PNG.png" alt="profile_image">
          </div>
          <div class="col">
          <img width="300px" height="300px" src="https://www.lewagon.com/assets/v4/logo-lewagon-9c19fb39a748cd3b1f49059ce0dc6c0dfc4cc2447d5a9a3e01bd2d5a214faf3c.svg" alt="profile_image">
          </div>
      </section>

</div>